
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[548] =
    {   0,
       15,   13,   14,   10,   13,   14,    1,   14,   12,   13,
       14,    8,   13,   14,    9,   13,   14,    8,   13,   14,
        8,   13,   14,    8,   13,   14,    8,   13,   14,    8,
       13,   14,    8,   13,   14,    6,    7,   13,   14,    8,
       13,   14,    8,   13,   14,    8,   13,   14,   11,   13,
       14,   11,   13,   14,   11,   13,   14,   11,   13,   14,
       11,   13,   14,   11,   13,   14,   11,   13,   14,   11,
       13,   14,   11,   13,   14,   11,   13,   14,   11,   13,
       14,   11,   13,   14,   11,   13,   14,   11,   13,   14,
       11,   13,   14,   11,   13,   14,   11,   13,   14,   11,

       13,   14,   11,   13,   14,   11,   13,   14,   11,   13,
       14,    5,    8,    4,    6,    7,   11,   11,   11,    3,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    3,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,    2,   11,   11,    3,   11,    3,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    3,   11,    3,
       11,   11,    3,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,    3,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    7,    7,    3,
       11,   11,    3,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,    3,   11,   11,   11,   11,
        3,   11,   11,   11,   11,   11,   11,   11,    3,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        3,   11,    3,   11,    3,   11,    3,   11,   11,   11,
        3,   11,   11,   11,   11,   11,   11,   11,   11,    3,
       11,    3,   11,   11,    3,   11,   11,   11,   11,   11,
       11,   11,    3,   11,   11,   11,   11,   11,    3,   11,
       11,   11,   11,   11,    3,   11,   11,   11,   11,   11,
        3,   11,   11,    3,   11,    3,   11,   11,   11,   11,
       11,   11,   11,   11,    2,   11,    3,   11,   11,   11,

       11,    3,   11,   11,   11,   11,    2,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    2,   11,    3,   11,   11,   11,    3,
       11,   11,   11,   11,   11,    3,   11,   11,    3,   11,
        3,   11,    3,   11,   11,    3,   11,   11,    3,   11,
        3,   11,   11,    3,   11,    3,   11,   11,    3,   11,
       11,    3,   11,    3,   11,   11,   11,   11,   11,   11,
       11,   11,    3,   11,   11,    3,   11,   11,   11,   11,
       11,   11,   11,   11,    3,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,    3,   11,   11,   11,   11,

       11,   11,   11,   11,    3,   11,    2,   11,    2,   11,
       11,   11,   11,   11,   11,   11,    3,   11,    3,   11,
        3,   11,   11,   11,   11,   11,   11,   11,   11,    3,
       11,   11,   11,   11,   11,   11,    3,   11,   11,    3,
       11,   11,   11,   11,    3,   11,    3,   11,   11,    3,
       11,   11,    3,   11,   11,    3,   11,   11,   11,   11,
       11,    3,   11,    3,   11,   11,    3,   11,   11,   11,
       11,   11,    3,   11,   11,    3,   11,    3,   11,   11,
       11,   11,    3,   11,   11,   11,   11,   11,    3,   11,
       11,    3,   11,   11,   11,    3,   11,   11,   11,   11,

       11,    3,   11,    3,   11,   11,    3,   11,    3,   11,
        3,   11,   11,   11,   11,   11,   11,    3,   11,   11,
        3,   11,    3,   11,    3,   11,   11,    3,   11,   11,
       11,   11,    3,   11,   11,   11,   11,    3,   11,   11,
       11,   11,   11,    3,   11,    3,   11
    } ;

static yyconst flex_int16_t yy_accept[392] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   18,
       21,   24,   27,   30,   33,   36,   40,   43,   46,   49,
       52,   55,   58,   61,   64,   67,   70,   73,   76,   79,
       82,   85,   88,   91,   94,   97,  100,  103,  106,  109,
      112,  113,  114,  115,  117,  117,  117,  118,  119,  120,
      122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
      132,  134,  135,  136,  137,  138,  139,  140,  141,  142,
      143,  145,  146,  148,  150,  151,  152,  153,  154,  155,
      156,  157,  158,  160,  162,  163,  165,  166,  167,  168,
      169,  170,  171,  172,  173,  174,  175,  176,  178,  179,

      180,  181,  182,  183,  184,  185,  186,  187,  188,  189,
      189,  190,  192,  193,  195,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  206,  208,  209,  210,  211,
      213,  214,  215,  216,  217,  218,  219,  221,  222,  223,
      224,  225,  226,  227,  228,  229,  230,  231,  233,  235,
      237,  239,  240,  241,  243,  244,  245,  246,  247,  248,
      249,  250,  252,  254,  255,  257,  258,  259,  260,  261,
      262,  263,  265,  266,  267,  268,  269,  271,  272,  273,
      274,  275,  277,  278,  279,  280,  281,  283,  284,  286,
      288,  289,  290,  291,  292,  293,  294,  295,  297,  299,

      300,  301,  302,  304,  305,  306,  307,  309,  310,  311,
      312,  313,  314,  315,  316,  317,  318,  319,  320,  321,
      322,  323,  324,  326,  328,  329,  330,  332,  333,  334,
      335,  336,  338,  339,  341,  343,  345,  346,  348,  349,
      351,  353,  354,  356,  358,  359,  361,  362,  364,  366,
      367,  368,  369,  370,  371,  372,  373,  375,  376,  378,
      379,  380,  381,  382,  383,  384,  385,  387,  388,  389,
      390,  391,  392,  393,  394,  395,  396,  398,  399,  400,
      401,  402,  403,  404,  405,  407,  409,  411,  412,  413,
      414,  415,  416,  417,  419,  421,  423,  424,  425,  426,

      427,  428,  429,  430,  432,  433,  434,  435,  436,  437,
      439,  440,  442,  443,  444,  445,  447,  449,  450,  452,
      453,  455,  456,  458,  459,  460,  461,  462,  464,  466,
      467,  469,  470,  471,  472,  473,  475,  476,  478,  480,
      481,  482,  483,  485,  486,  487,  488,  489,  491,  492,
      494,  495,  496,  498,  499,  500,  501,  502,  504,  506,
      507,  509,  511,  513,  514,  515,  516,  517,  518,  520,
      521,  523,  525,  527,  528,  530,  531,  532,  533,  535,
      536,  537,  538,  540,  541,  542,  543,  544,  546,  548,
      548

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    5,    5,    5,    6,    7,
        8,    9,   10,    5,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    5,   16,
       17,   18,    1,    5,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
        5,    1,    5,    5,   35,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   35,   61,   62,   63,   64,   65,   66,   67,
       68,   69,    5,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[392] =
    {   0,
        0,    0,  110,  818,  818,  818,  818,  818,  818,   61,
       63,   58,   60,   99,   65,   67,   88,   67,   70,   57,
       68,   76,   97,  101,  121,   63,    0,  121,  122,   64,
      149,  189,  125,   89,  180,  158,  158,   80,  215,   67,
      818,  818,  818,  150,   89,  178,    0,   91,  151,  106,
      171,  171,  182,  177,  208,  215,  217,  206,  190,  217,
      217,  209,  237,  238,  231,  243,  230,  219,  234,  239,
        0,  244,  267,    0,  264,  266,  256,  268,  255,  270,
      265,  278,    0,    0,  284,    0,  271,  290,  280,  288,
      306,  305,  314,  290,  310,  281,  313,    0,  313,  297,

      327,  315,  310,  331,  322,  327,  340,  333,  364,   84,
       78,    0,  353,    0,  349,  349,  363,  360,  364,  366,
      355,  355,  358,  359,  365,    0,  380,  369,  380,    0,
      368,  381,  370,  387,  392,  399,    0,  398,  390,  394,
      405,  395,  407,  412,  415,  405,  414,    0,    0,    0,
        0,  419,  410,    0,  414,  438,  411,  440,  418,  429,
      429,    0,    0,  419,    0,  431,  427,  440,  442,  452,
      453,    0,  458,  446,  459,  453,    0,  457,  465,  470,
      456,    0,  452,  465,  476,  474,    0,  477,    0,    0,
      469,  470,  483,  478,  478,  486,  483,    0,    0,  501,

      488,  503,    0,  497,  494,  496,    0,  505,  499,  511,
      508,  519,  511,  524,  520,  524,  531,  528,  533,  522,
      539,  540,    0,    0,  529,  549,    0,  534,  544,  545,
      546,    0,  560,    0,    0,    0,  551,    0,  561,    0,
        0,  562,    0,    0,  568,    0,  559,    0,  557,  563,
      559,  562,  573,  569,  568,  570,    0,  582,    0,  576,
      583,  588,  597,  596,  597,  601,    0,  591,  598,  599,
      596,  598,  615,  617,  624,  611,    0,  622,  610,  622,
      627,  626,  629,  633,    0,    0,    0,  625,  641,  623,
      625,  645,  644,    0,    0,    0,  634,  630,  634,  635,

      655,  644,  654,    0,  652,  666,  647,  653,  659,    0,
      664,    0,  661,  667,  663,    0,    0,  671,    0,  673,
        0,  668,    0,  676,  688,  689,  676,    0,    0,  698,
        0,  686,  687,  698,  695,    0,  706,    0,    0,  706,
      694,  698,    0,  693,  699,  702,  722,    0,  708,    0,
      709,  711,    0,  712,  729,  712,  729,    0,    0,  734,
        0,    0,    0,  724,  725,  727,  737,  747,    0,  750,
        0,    0,    0,  736,    0,  737,  735,  738,    0,  747,
      753,  755,    0,  753,  754,  757,  759,    0,    0,  818,
       74

    } ;

static yyconst flex_int16_t yy_def[392] =
    {   0,
      390,    1,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      390,  390,  390,  390,  390,  390,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  390,  390,
      390,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,    0,
      390

    } ;

static yyconst flex_int16_t yy_nxt[888] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    8,   11,   12,
       13,   14,   15,   16,   17,   18,    8,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   27,   27,   29,
       30,   31,   32,   33,   27,   34,   35,   36,   37,   38,
       39,   40,   27,   27,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   27,   27,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   27,   27,   41,
       43,   44,   42,   44,   42,   47,   42,   42,   45,   42,
       44,   42,   42,   42,   42,   42,   42,   42,   48,   46,
       51,  111,   49,   50,   55,   70,   78,  111,  103,  108,

       52,   56,  109,   53,   42,   57,   42,   90,   58,  390,
       54,   91,  112,  390,   48,   46,   51,   49,   50,   59,
       55,   70,   78,   60,  103,  108,   52,   56,   53,   61,
       62,   57,   63,   90,   58,   54,  114,   91,  112,   65,
       75,  390,   64,   88,   71,   59,  390,   66,   76,   60,
       67,   72,   73,   68,   77,   61,   62,   74,   63,   69,
       89,   45,  114,   44,  390,   65,   75,   64,  390,   88,
       71,   79,   46,   66,   76,   80,   67,   72,   73,   68,
       77,   81,   74,   97,   69,   89,  113,  110,  110,  101,
       98,  111,  390,   99,  102,  115,  390,   79,   46,  390,

      100,   80,   92,  116,  117,   93,   94,   81,   82,   97,
       95,  113,   83,  390,  118,  101,   98,   96,   99,  102,
       84,  115,   85,  390,   86,  100,  124,   87,   92,  116,
      117,   93,   94,  121,   82,  122,   95,  123,   83,  118,
      104,  105,   96,  119,  120,  129,   84,  106,   85,   86,
      107,  124,   87,  125,  137,  127,  126,  128,  130,  121,
      133,  122,  136,  123,  131,  138,  104,  105,  119,  120,
      129,  132,  134,  106,  135,  107,  139,  140,  125,  137,
      127,  126,  128,  145,  130,  146,  133,  147,  136,  148,
      131,  138,  141,  142,  390,  149,  143,  132,  134,  150,

      135,  139,  151,  140,  144,  152,  153,  390,  154,  145,
      155,  146,  156,  147,  157,  148,  168,  390,  141,  142,
      149,  166,  143,  390,  158,  150,  159,  151,  167,  144,
      173,  152,  153,  154,  161,  169,  155,  176,  156,  160,
      157,  168,  162,  163,  390,  177,  164,  166,  170,  165,
      158,  171,  159,  174,  167,  172,  173,  178,  390,  179,
      161,  169,  180,  176,  175,  160,  181,  162,  182,  163,
      177,  183,  164,  170,  165,  184,  171,  109,  185,  174,
      172,  186,  187,  178,  179,  188,   46,  180,  189,  175,
      190,  191,  181,  182,  192,  193,  194,  183,  195,  196,

      197,  184,  198,  200,  185,  199,  202,  186,  187,  203,
      204,  188,   46,  201,  189,  190,  191,  205,  206,  192,
      193,  194,  207,  208,  195,  196,  197,  209,  198,  200,
      199,  202,  210,  211,  212,  203,  204,  213,  215,  201,
      214,  216,  218,  205,  206,  217,  390,  222,  207,  208,
      225,  226,  227,  209,  228,  229,  230,  210,  219,  211,
      212,  223,  220,  213,  215,  214,  231,  216,  218,  224,
      217,  221,  222,  232,  233,  234,  225,  226,  227,  228,
      235,  229,  230,  236,  219,  237,  239,  223,  220,  238,
      240,  241,  231,  242,  243,  224,  244,  221,  245,  232,

      233,  234,  246,  247,  390,  248,  235,  249,  236,  250,
      252,  237,  239,  251,  238,  253,  240,  241,  242,  243,
      254,  255,  244,  256,  245,  257,  258,  261,  246,  247,
      248,  259,  249,  260,  262,  250,  252,  263,  251,  264,
      267,  253,  268,  265,  271,  254,  269,  255,  256,  272,
      273,  257,  258,  261,  266,  274,  259,  275,  260,  262,
      270,  276,  277,  263,  278,  264,  267,  279,  268,  265,
      271,  280,  269,  281,  282,  272,  273,  283,  284,  266,
      285,  274,  275,  286,  287,  270,  288,  276,  277,  278,
      289,  390,  290,  279,  291,  294,  280,  292,  293,  281,

      282,  295,  300,  283,  284,  296,  285,  297,  298,  286,
      287,  299,  288,  301,  302,  303,  289,  290,  304,  305,
      291,  294,  292,  293,  306,  390,  307,  295,  300,  308,
      296,  309,  297,  310,  298,  311,  312,  299,  313,  301,
      302,  303,  314,  316,  304,  305,  315,  317,  318,  319,
      306,  307,  320,  321,  322,  308,  323,  309,  310,  324,
      311,  325,  312,  326,  313,  327,  328,  332,  314,  316,
      329,  315,  317,  330,  318,  319,  331,  333,  320,  321,
      322,  334,  323,  335,  337,  324,  325,  336,  326,  338,
      339,  327,  328,  332,  340,  329,  341,  343,  330,  342,

      344,  331,  345,  333,  346,  348,  334,  347,  349,  335,
      337,  350,  336,  351,  338,  339,  352,  353,  354,  340,
      355,  356,  341,  343,  342,  344,  357,  358,  345,  359,
      346,  348,  347,  360,  349,  361,  362,  350,  351,  363,
      364,  366,  352,  353,  354,  365,  355,  356,  367,  368,
      369,  371,  357,  358,  359,  370,  372,  374,  360,  373,
      361,  362,  375,  376,  363,  377,  364,  366,  378,  380,
      365,  379,  381,  367,  368,  382,  369,  371,  383,  384,
      370,  385,  372,  374,  373,  386,  387,  375,  388,  376,
      389,  377,  390,  390,  378,  380,  379,  381,  390,  390,

      382,  390,  390,  390,  383,  384,  390,  385,  390,  390,
      390,  386,  387,  390,  388,  390,  389,    3,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390
    } ;

static yyconst flex_int16_t yy_chk[888] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   10,
       11,   12,   10,   13,   12,  391,   13,   15,   16,   11,
       16,   15,   18,   18,   18,   19,   19,   19,   20,   16,
       21,  111,   20,   20,   22,   26,   30,  110,   38,   40,

       21,   22,   45,   21,   17,   22,   14,   34,   22,    3,
       21,   34,   48,    0,   20,   16,   21,   20,   20,   23,
       22,   26,   30,   23,   38,   40,   21,   22,   21,   23,
       24,   22,   24,   34,   22,   21,   50,   34,   48,   25,
       29,    0,   24,   33,   28,   23,    0,   25,   29,   23,
       25,   28,   28,   25,   29,   23,   24,   28,   24,   25,
       33,   44,   50,   44,    0,   25,   29,   24,    0,   33,
       28,   31,   44,   25,   29,   31,   25,   28,   28,   25,
       29,   31,   28,   36,   25,   33,   49,   46,   46,   37,
       36,   46,    0,   36,   37,   51,    0,   31,   44,    0,

       36,   31,   35,   52,   53,   35,   35,   31,   32,   36,
       35,   49,   32,    0,   54,   37,   36,   35,   36,   37,
       32,   51,   32,    0,   32,   36,   59,   32,   35,   52,
       53,   35,   35,   56,   32,   57,   35,   58,   32,   54,
       39,   39,   35,   55,   55,   62,   32,   39,   32,   32,
       39,   59,   32,   60,   68,   61,   60,   61,   63,   56,
       65,   57,   67,   58,   64,   69,   39,   39,   55,   55,
       62,   64,   66,   39,   66,   39,   70,   72,   60,   68,
       61,   60,   61,   75,   63,   76,   65,   77,   67,   78,
       64,   69,   73,   73,    0,   79,   73,   64,   66,   80,

       66,   70,   81,   72,   73,   82,   85,    0,   87,   75,
       88,   76,   89,   77,   90,   78,   96,    0,   73,   73,
       79,   94,   73,    0,   91,   80,   91,   81,   95,   73,
      100,   82,   85,   87,   92,   97,   88,  102,   89,   91,
       90,   96,   92,   93,    0,  103,   93,   94,   97,   93,
       91,   99,   91,  101,   95,   99,  100,  104,    0,  105,
       92,   97,  106,  102,  101,   91,  107,   92,  108,   93,
      103,  113,   93,   97,   93,  115,   99,  109,  116,  101,
       99,  117,  118,  104,  105,  119,  109,  106,  120,  101,
      121,  122,  107,  108,  123,  123,  124,  113,  125,  127,

      128,  115,  129,  132,  116,  131,  133,  117,  118,  134,
      135,  119,  109,  132,  120,  121,  122,  136,  138,  123,
      123,  124,  139,  140,  125,  127,  128,  141,  129,  132,
      131,  133,  142,  143,  144,  134,  135,  145,  147,  132,
      146,  152,  155,  136,  138,  153,    0,  157,  139,  140,
      159,  160,  161,  141,  164,  166,  167,  142,  156,  143,
      144,  158,  156,  145,  147,  146,  168,  152,  155,  158,
      153,  156,  157,  169,  170,  171,  159,  160,  161,  164,
      173,  166,  167,  174,  156,  175,  178,  158,  156,  176,
      179,  180,  168,  181,  183,  158,  184,  156,  185,  169,

      170,  171,  186,  188,    0,  191,  173,  192,  174,  193,
      195,  175,  178,  194,  176,  196,  179,  180,  181,  183,
      197,  200,  184,  201,  185,  202,  204,  208,  186,  188,
      191,  205,  192,  206,  209,  193,  195,  210,  194,  211,
      213,  196,  214,  212,  216,  197,  215,  200,  201,  217,
      218,  202,  204,  208,  212,  219,  205,  220,  206,  209,
      215,  221,  222,  210,  225,  211,  213,  226,  214,  212,
      216,  228,  215,  229,  230,  217,  218,  231,  233,  212,
      237,  219,  220,  239,  242,  215,  245,  221,  222,  225,
      247,    0,  249,  226,  250,  253,  228,  251,  252,  229,

      230,  254,  260,  231,  233,  255,  237,  256,  258,  239,
      242,  258,  245,  261,  262,  263,  247,  249,  264,  265,
      250,  253,  251,  252,  266,    0,  268,  254,  260,  269,
      255,  270,  256,  271,  258,  272,  273,  258,  274,  261,
      262,  263,  275,  278,  264,  265,  276,  279,  280,  281,
      266,  268,  282,  283,  284,  269,  288,  270,  271,  289,
      272,  290,  273,  291,  274,  292,  293,  300,  275,  278,
      297,  276,  279,  298,  280,  281,  299,  301,  282,  283,
      284,  302,  288,  303,  306,  289,  290,  305,  291,  307,
      308,  292,  293,  300,  309,  297,  311,  314,  298,  313,

      315,  299,  318,  301,  320,  324,  302,  322,  325,  303,
      306,  326,  305,  327,  307,  308,  330,  332,  333,  309,
      334,  335,  311,  314,  313,  315,  337,  340,  318,  341,
      320,  324,  322,  342,  325,  344,  345,  326,  327,  346,
      347,  351,  330,  332,  333,  349,  334,  335,  352,  354,
      355,  357,  337,  340,  341,  356,  360,  365,  342,  364,
      344,  345,  366,  367,  346,  368,  347,  351,  370,  376,
      349,  374,  377,  352,  354,  378,  355,  357,  380,  381,
      356,  382,  360,  365,  364,  384,  385,  366,  386,  367,
      387,  368,    0,    0,  370,  376,  374,  377,    0,    0,

      378,    0,    0,    0,  380,  381,    0,  382,    0,    0,
        0,  384,  385,    0,  386,    0,  387,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "b023040001.l"
#line 2 "b023040001.l"
#include <stdio.h>
#include <ctype.h>
#include <string.h>
unsigned charCount = 0, lineCount = 1;
#define typeNum 8
#define MAX_BUF_SIZE 1024
char *type[typeNum] = { "integer", "real", "ID", "reserved word", "string", "symbol", "comment", "Unrecognized character" };
char *prevToken;
char buf[MAX_BUF_SIZE];
int declaration = 0;
int state = 1;
int rcmp( char* a, int a_len, const char* b, int b_len )
{
	if( a_len == b_len )
	{
		a_len--;
		while( a_len >= 0 )
		{
			if( tolower( a[a_len] ) != tolower( b[a_len] ) )
				return 1;
			a_len--;
		}
		return 0;
	}
	return 1;
}

#line 881 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 43 "b023040001.l"

#line 1070 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 391 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 818 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 44 "b023040001.l"
{ 
				if( state != 1 && state != 4 )
					printf("Line: %u, 1st char: %u, expect a “';'”.\n", lineCount, charCount + 1 );					
				state = 1;
				lineCount++; 
				charCount = 0;
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "b023040001.l"
{
				if( state == -1 || state == -2 )
				{
					strcat( buf, yytext );
				}
				else
				{
					state = 2;
					printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, yytext, type[3] ); 
					charCount += yyleng; 
					prevToken = type[3];	
				}
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "b023040001.l"
{
				if( state == -1 || state == -2 )
				{
					strcat( buf, yytext );
				}
				else if( rcmp( yytext, yyleng, "var", 3 ) == 0 )
				{
					declaration = 1;
					memset( buf, 0, MAX_BUF_SIZE );
				}
				else if( rcmp( yytext, yyleng, "begin", 5 ) == 0 )
				{
					declaration = 0;
					state = 1;
				}
				else if( rcmp( yytext, yyleng, "end", 3 ) == 0 )
					state = 4;
				else if( ( rcmp( yytext, yyleng, "then", 4 ) == 0 ) || ( rcmp( yytext, yyleng, "do", 2 ) == 0 ) )
					state = 1; 
				printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, yytext, type[3] ); 
				charCount += yyleng; 
				prevToken = type[3];
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 87 "b023040001.l"
{
				if( state == -1 )
				{
					printf("“%s” is an invalid “%s”.\n", buf, type[2] );
				}
				else if ( state == -2 )
				{
					printf("“%s” is an invalid “%s”.\n", buf, type[1] );
				}
				printf("Line: %u, 1st char: %u, “%s” is an invalid “%s”.\n", lineCount, charCount + 1, yytext, type[6] ); 
				charCount += yyleng;
				state = 4;
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "b023040001.l"
{	
				int c, temp_i = 0, temp_i1 = 0; memset( buf, 0, MAX_BUF_SIZE );
				while( 1 )
				{
					while( (c = input()) != '*' && c!= EOF )
					{
						buf[temp_i1] = c;
						temp_i1++;
						if( c == '\n' )
							temp_i++;
					}
					if( c == '*' )
					{
						buf[temp_i1] = c;
						temp_i1++;
						while( ( c = input() ) == '*' )
						{
							buf[temp_i1] = c;
							temp_i1++;
						}
						if( c == ')' )
						{
							buf[temp_i1] = c;
							temp_i1++;
							buf[temp_i1] = '\0';
							printf("Line: %u, 1st char: %u, “%s%s” is a “%s”.\n", lineCount, charCount + 1, yytext, buf, type[6] ); 
							charCount += ( yyleng + temp_i1 );
							lineCount += temp_i;
							prevToken = type[6];
							break;
						}
					}
					if( c == EOF )
					{
						printf( "EOF in comment" );
						break;
					}
				}
			}			
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 139 "b023040001.l"
{ 
				if( state == 1 )
				{
					printf("Line: %u, 1st char: %u, ", lineCount, charCount + 1 );
					memset( buf, 0, MAX_BUF_SIZE );
					strcat( buf, yytext );
					state = -1;
				}
				else if( state == -1 || state == -2 )
				{
					strcat( buf, yytext );
				}
				else if( prevToken == type[0] && ( yytext[0] == '+' || yytext[0] == '-' ) )
				{
					REJECT;			
				}
				else
				{
					memset( buf, 0, MAX_BUF_SIZE );
					strcat( buf, yytext );
					int c = input();
					if( c == '.' )
					{
						printf("Line: %u, 1st char: %u, ", lineCount, charCount + 1 );
//						memset( buf, 0, MAX_BUF_SIZE );
//						strcat( buf, yytext );
						state = -2;
					}
					else
					{
						unput( c );
						printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, buf, type[0] ); 
						prevToken = type[0];
					}
				}
				charCount += yyleng; 
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 176 "b023040001.l"
{ 
				if( prevToken == type[0] && ( yytext[0] == '+' || yytext[0] == '-' ) )
				{
					REJECT;			
				}
				else if( state == -1 || state == -2 )
				{
					strcat( buf, yytext );
				}
				
				if( yytext[yyleng - 1] == '0' )
					printf("Line: %u, 1st char: %u, “%s” is an invalid “%s”.\n", lineCount, charCount + 1, yytext, type[1] );
				else
					printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, yytext, type[1] ); 
				charCount += yyleng;
				prevToken = type[1];
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 193 "b023040001.l"
{ 	
				if( ( state == 1 ) )
				{

					printf("Line: %u, 1st char: %u, ", lineCount, charCount + 1 );
					memset( buf, 0, MAX_BUF_SIZE );
					strcat( buf, yytext );
					state = -1;
					
				}
				else if( state == -1 || state == -2 )
				{
					strcat( buf, yytext );
				}
				else if( strcmp( yytext, "." ) == 0 )
				{
					int c = input(), temp_i = 0;
					if( c <= '9' && c >= '0' || c == 'E' || c == 'e' )
					{
						memset( buf, 0, MAX_BUF_SIZE );
						while( c <= '9' && c >= '0' )
						{
							buf[temp_i] = c;
							c = input();
						}
						printf("Line: %u, 1st char: %u, “%s%s” is an invalid “%s”.\n", lineCount, charCount + 1, yytext, buf, type[1] ); 
					}
					else					
					{
						printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, yytext, type[5] ); 
						prevToken = type[5];
					}
					unput( c );	
				}	
				else 	
				{
					if( ( ( strcmp( yytext, ":" ) == 0 ) || ( strcmp( yytext, ":=" ) == 0 ) ) && ( state == 2 ) )
						state = 3;
					if( strcmp( yytext, ";" ) == 0 )
						state = 1;
					printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, yytext, type[5] ); 
					prevToken = type[5];
				}
				charCount += yyleng;
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 238 "b023040001.l"
{
				int c, len = 0, temp_i = 0;
				memset( buf, 0, MAX_BUF_SIZE );
				while( c = input() )
				{
					buf[temp_i++] = c;
					if( c == '\'' )
					{
						c = input();
						if( c == '\'' )
						{
							buf[temp_i++] = c;
						}
						else
						{
							if( len > 30 )
							{
								printf("Line: %u, 1st char: %u,“%s%s” is an invalid “%s”\n", lineCount, charCount + 1, yytext, buf, type[4] );
								break;
							}
							printf("Line: %u, 1st char: %u, “%s%s” is a “%s”.\n", lineCount, charCount + 1, yytext, buf, type[4] ); 
							prevToken = type[4];
							break;
						}
					}
					else if( c == '\n' || c == '\r' )
					{
						if( c == '\n' )
							state = 1;
						else
							state = 4;
						buf[--temp_i] = '\0';
						printf("Line: %u, 1st char: %u, “%s%s” is an invalid “%s”.\n", lineCount, charCount + 1, yytext, buf, type[4] ); 
						break;
					}
					len++;
				} 
				unput( c );
				charCount += ( temp_i + 1 );
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 278 "b023040001.l"
{	
				if( state == -1 )
				{
					printf("“%s” is an invalid “ID”.\n", buf );
					state = 3;
				}
				charCount += yyleng;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 286 "b023040001.l"
{ 
				if( state == -1 || state == -2 )
					strcat( buf, yytext );
				else
				{
					if( state == 1 )
						state = 2;
					if( yyleng > 30 )
						printf("Line: %u, 1st char: %u, “%s” is an invalid “%s”.\n", lineCount, charCount + 1, yytext, type[2] ); 
					else					
						printf("Line: %u, 1st char: %u, “%s” is a “%s”.\n", lineCount, charCount + 1, yytext, type[2] ); 
					prevToken = type[2];
				}
				charCount += yyleng;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 301 "b023040001.l"
{};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 302 "b023040001.l"
{ charCount++; printf("\n>(-_-)<\n>(-_-)< line no.%-5u : type = %s , \n>(-_-)< \t\tcharecter = %u\n>(-_-)<\n\n", lineCount, type[7], (unsigned)yytext[0] );}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 303 "b023040001.l"
ECHO;
	YY_BREAK
#line 1479 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 391 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 391 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 390);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 303 "b023040001.l"


main(){  
	yylex(); 
	return 0;
}

